apiVersion: v1
appVersion: 7.0.0
description: "A Helm chart for Activiti Cloud Example Connector"
icon: "https://salaboy.files.wordpress.com/2018/01/acitiviti_icon_fullcolor_github_400x400.png"
name: example-cloud-connector
version: 1.0.3
